# Generated by Django 4.0.3 on 2022-03-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Shop title')),
                ('adress', models.TextField(verbose_name='Shop adress')),
                ('phone', models.TextField(verbose_name='Shop phone number')),
                ('shop_image_src', models.CharField(max_length=255, verbose_name='image')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'db_table': 'Shops',
            },
        ),
    ]
