# Generated by Django 4.0.3 on 2022-03-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Action name')),
                ('text', models.TextField(verbose_name='Action text')),
                ('imageUrl', models.CharField(max_length=255, verbose_name='image')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Action created')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'db_table': 'Actions',
            },
        ),
    ]
