# Generated by Django 4.0.3 on 2022-03-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='PizzaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Pizza name')),
                ('text', models.TextField(verbose_name='Post data')),
                ('price', models.IntegerField(default=15)),
                ('image', models.CharField(max_length=255, verbose_name='image')),
                ('cathegory', models.ManyToManyField(related_name='pizza', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Pizza',
                'verbose_name_plural': 'Pizza',
                'db_table': 'Pizza',
            },
        ),
    ]
